import {ORDER_CALL, ORDER_CAR, ORDER_CONTRACT, ORDER_DESTINATION, ORDER_DISTANCE, ORDER_ERROR, ORDER_LOADING, ORDER_MOVEDATE, ORDER_MOVEFORM, ORDER_NAME, ORDER_OPTION_1, ORDER_OPTION_2, ORDER_PACKINGDATE, ORDER_PHONE, ORDER_STARTINGPOINT} from '../types/order.type'

export const getDistance = (distance)=>{

}