export const EDUATTEND_LIST_SUCCESS = "EDUATTEND_LIST_SUCCESS";
export const EDUATTEND_LIST_LOADING = "EDUATTEND_LIST_LOADING";
export const EDUATTEND_LIST_ERROR = "EDUATTEND_LIST_ERROR";

export const EDUPOINT_USE_SUCCESS = "EDUPOINT_USE_SUCCESS";
export const EDUPOINT_USE_LOADING = "EDUPOINT_USE_LOADING";
export const EDUPOINT_USE_ERROR = "EDUPOINT_USE_ERROR";

