export const GET_MOVEDAY_SUCCESS = "GET_MOVEDAY_SUCCESS";
export const GET_MOVEDAY_LOADING = "GET_MOVEDAY_LOADING";
export const GET_MOVEDAY_ERROR = "GET_MOVEDAY_ERROR";
export const GET_MOVEDAY_INIT = "GET_MOVEDAY_INIT";