
export const ORDER_NAME = 'ORDER_NAME';;
export const ORDER_PHONE = 'ORDER_PHONE';
export const ORDER_CALL = 'ORDER_CALL';
export const ORDER_MOVEFORM = 'ORDER_MOVEFORM';
export const ORDER_MOVEDATE = 'ORDER_MOVEDATE';
export const ORDER_PACKINGDATE = 'ORDER_PACKINGDATE';
export const ORDER_STARTINGPOINT = 'ORDER_STARTINGPOINT';
export const ORDER_DESTINATION = 'ORDER_DESTINATION';
export const ORDER_DISTANCE = 'ORDER_DISTANCE';
export const ORDER_OPTION_1 = 'ORDER_OPTION_1';
export const ORDER_OPTION_2 = 'ORDER_OPTION_2';
export const ORDER_CAR = 'ORDER_CAR';
export const ORDER_CONTRACT = 'ORDER_CONTRACT';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_ERROR = 'ORDER_ERROR';



