export const PICTURECHECK_LIST_SUCCESS = "PICTURECHECK_LIST_SUCCESS";
export const PICTURECHECK_LIST_LOADING = "PICTURECHECK_LIST_LOADING";
export const PICTURECHECK_LIST_ERROR = "PICTURECHECK_LIST_ERROR";


export const PICTURECHECK_DETAIL_SUCCESS = "PICTURECHECK_DETAIL_SUCCESS";
export const PICTURECHECK_DETAIL_LOADING = "PICTURECHECK_DETAIL_LOADING";
export const PICTURECHECK_DETAIL_ERROR = "PICTURECHECK_DETAIL_ERROR";