export const SUGGESTION_LOADING = "SUGGESTION_LOADING";
export const SUGGESTION_ERROR = "SUGGESTION_ERROR";
export const SUGGESTION_SUCCESS = "SUGGESTION_SUCCESS";
export const SUGGESTION_INIT = "SUGGESTION_INIT";