export const WARNING_LIST_SUCCESS = "WARNING_LIST_SUCCESS";
export const WARNING_LIST_LOADING = "WARNING_LIST_LOADING";
export const WARNING_LIST_ERROR = "WARNING_LIST_ERROR";
export const WARNING_LIST_CONCAT_SUCCESS = "WARNING_LIST_CONCAT_SUCCESS";
export const WARNING_LIST_CONCAT_LOADING = "WARNING_LIST_CONCAT_LOADING";


export const WARNING_DETAIL_SUCCESS = "WARNING_DETAIL_SUCCESS";
export const WARNING_DETAIL_LOADING = "WARNING_DETAIL_LOADING";
export const WARNING_DETAIL_ERROR = "WARNING_DETAIL_ERROR";