 export const WORKINGDAY_SUCCESS = "WORKINGDAY_SUCCESS";
 export const WORKINGDAY_ERROR = "WORKINGDAY_ERROR";
 export const WORKINGDAY_LOADING = "WORKINGDAY_LOADING";

 export const WORKINGDAY_DETAIL_SUCCESS = "WORKINGDAY_DETAIL_SUCCESS";
 export const WORKINGDAY_DETAIL_ERROR = "WORKINGDAY_DETAIL_ERROR";
 export const WORKINGDAY_DETAIL_LOADING = "WORKINGDAY_DETAIL_LOADING";